# Generated by Django 3.1.6 on 2021-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoffeeMachine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SKU_number", models.CharField(max_length=6)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("coffe_machine_large", "Coffee machine large"),
                            ("coffe_machine_small", "Coffee machine small"),
                            ("espresso_machine", "Espresso machine"),
                        ],
                        max_length=20,
                    ),
                ),
                ("water_line_compatible", models.BooleanField()),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("base_model", "Base model"),
                            ("premium_model", "Premium model"),
                            ("deluxe_model", "Deluxe model"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
