# Generated by Django 3.1.6 on 2021-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_add_coffee_machine"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoffeePod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SKU_number", models.CharField(max_length=6)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("coffe_pod_large", "Coffee pod large"),
                            ("coffe_pod_small", "Coffee pod small"),
                            ("espresso_pod", "Espresso pod"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "coffee_flavor",
                    models.CharField(
                        choices=[
                            ("coffee_flavor_vanilla", "Coffee flavor vanilla"),
                            ("coffee_flavor_caramel", "Coffee flavor caramel"),
                            ("coffee_flavor_psl", "Coffee flavor psl"),
                            ("coffee_flavor_mocha", "Coffee flavor mocha"),
                            ("coffee_flavor_hazelnut", "Coffee flavor hazelnut"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "pack_size",
                    models.CharField(
                        choices=[
                            ("one_dozen", "One dozen"),
                            ("three_dozen", "Three dozen"),
                            ("five_dozen", "Five dozen"),
                            ("seven_dozen", "Seven dozen"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
