# Generated by Django 3.1.6 on 2021-02-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_add_coffee_pod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeemachine",
            name="SKU_number",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="coffeepod",
            name="SKU_number",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
