# Generated by Django 3.1.6 on 2021-02-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_sku_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeemachine",
            name="model_type",
            field=models.CharField(
                choices=[("base", "Base"), ("premium", "Premium"), ("deluxe", "Deluxe")], max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="coffeemachine",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("large", "Coffee machine large"),
                    ("small", "Coffee machine small"),
                    ("espresso", "Espresso machine"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coffeepod",
            name="coffee_flavor",
            field=models.CharField(
                choices=[
                    ("vanilla", "Vanilla"),
                    ("caramel", "Caramel"),
                    ("psl", "Psl"),
                    ("mocha", "Mocha"),
                    ("hazelnut", "Hazelnut"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="coffeepod",
            name="pack_size",
            field=models.CharField(
                choices=[("1", "One dozen"), ("3", "Three dozen"), ("5", "Five dozen"), ("7", "Seven dozen")],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="coffeepod",
            name="product_type",
            field=models.CharField(
                choices=[("large", "Coffee pod large"), ("small", "Coffee pod small"), ("espresso", "Espresso pod")],
                max_length=20,
            ),
        ),
    ]
